# OpenRouteService API Key (FREE)
# Get yours at: https://openrouteservice.org/dev/#/signup

ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjdjMWIzNjI0OTkyNzQ0YjA5MTYyNTVmYTEyNTU5YmI4IiwiaCI6Im11cm11cjY0In0="